/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSkinsRouteImport } from './routes/api/skins'
import { Route as ApiSkinsIdRouteImport } from './routes/api/skins.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkinsRoute = ApiSkinsRouteImport.update({
  id: '/api/skins',
  path: '/api/skins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkinsIdRoute = ApiSkinsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSkinsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/skins': typeof ApiSkinsRouteWithChildren
  '/api/skins/$id': typeof ApiSkinsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/skins': typeof ApiSkinsRouteWithChildren
  '/api/skins/$id': typeof ApiSkinsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/skins': typeof ApiSkinsRouteWithChildren
  '/api/skins/$id': typeof ApiSkinsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/skins' | '/api/skins/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/skins' | '/api/skins/$id'
  id: '__root__' | '/' | '/api/skins' | '/api/skins/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSkinsRoute: typeof ApiSkinsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skins': {
      id: '/api/skins'
      path: '/api/skins'
      fullPath: '/api/skins'
      preLoaderRoute: typeof ApiSkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skins/$id': {
      id: '/api/skins/$id'
      path: '/$id'
      fullPath: '/api/skins/$id'
      preLoaderRoute: typeof ApiSkinsIdRouteImport
      parentRoute: typeof ApiSkinsRoute
    }
  }
}

interface ApiSkinsRouteChildren {
  ApiSkinsIdRoute: typeof ApiSkinsIdRoute
}

const ApiSkinsRouteChildren: ApiSkinsRouteChildren = {
  ApiSkinsIdRoute: ApiSkinsIdRoute,
}

const ApiSkinsRouteWithChildren = ApiSkinsRoute._addFileChildren(
  ApiSkinsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSkinsRoute: ApiSkinsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
